language: c
os:
  - linux
  - osx
env:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.10
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - eval `opam config env`
  - opam repository add satysfi-external https://github.com/gfngfn/satysfi-external-repo.git
  - opam repository add camlpdf-yyu ./camlpdf
  - opam update
  - opam pin add -y --no-action satysfi .
  - opam install -y --deps-only satysfi
script:
  - make all
